### ISSUE TITLE
Reward Calculation - Suggestion

### ISSUE THREAD

**Issue by kaleb-keny** [yieldfarming/yield-farming#1]
Hey @penandlim thank you for developing this really cool tool... Helps me a lot actually. I read very little js, but I kind of understood how you're pulling the rewards by going to the last 7 blocks. Another way to do this that applies for most of the contracts, and is less prone to issues (in case the timing of rewards change or number of blocks per week change) is to use the contract themselves. 
Example  the sXAU staking contract
https://etherscan.io/address/0x8302fe9f0c509a996573d3cc5b0d5d51e4fdd5ec#readContract
you just get the following inputs:
- `RewardRate` = 13243828910164889 (which is just reward per second)
- `Duration` = 604800 (which is just 1 week in seconds) 
And calculate the rewards:
`Weekly Rewards` = `RewardRate*Duration/1e18`= 8009.86772487

Thanks again for developing this for the snx community

**Comment by penandlim** [comment]
Hey kaleb. Glad I can be helpful to the SNX community!

This definitely seems like a better way of calculating the rewards. Thanks for raising the issue I will look into this.

**Comment by penandlim** [comment]
Added with https://github.com/yieldfarming/yieldfarming/commit/657e52a9ff1fa77c63285a9e5128b2d433f07c60

Thanks again @kaleb-keny !
