### ISSUE TITLE
withdraw issue on weeb tend- v3

### ISSUE THREAD

**Issue by scrypto19** [yieldfarming/yield-farming#26]
I originally deposited this amount: 
https://etherscan.io/tx/0x91f4f5f82e8c5726dafc0a16edc553c7e290720088868b5d1871c0dd76a42768

when i saw the notification that V3 was having issue to withdraw I ended getting only .002% back: 

https://etherscan.io/tx/0xc797f34e7b48698b81d348a8589a92f0965e8546373ee7395e95049f733980b5

any help would be great

**Comment by penandlim** [comment]
Resolved. Closing the issue.
