### ISSUE TITLE
BAL is live!

### ISSUE THREAD

**Issue by mattiascaricato** [yieldfarming/yield-farming#4]
Hi there, $BAL went live today but we are still showing "WARNING: BAL is not distributed yet.". I'd like to know how can we help to add it to the output.

Thanks for such great tool!

**Comment by penandlim** [comment]
Hey @mattiascaricato Even though the warning sign is there, the BAL balance should be displayed like below. 

![image](https://user-images.githubusercontent.com/4276174/85473442-17dff180-b568-11ea-8ce0-6701981e5a1c.png)

If it doesnt show, your browser may be cacheing the resource files. Try doing a hard refresh https://www.zesty.io/mindshare/marketing-technology/how-to-hard-refresh/

Also note that unlike SNX or BPT which gets updated every block, BAL is manually distributed weekly by BalancerLabs team, so there is no good way of estimating your BAL per week.

If you happen to find any useful calculation tool, please do let me know on this thread! I will try to get it integrated if I can.

Thanks for your support

**Comment by mattiascaricato** [comment]
@penandlim thanks for your prompt response! It's weird because I don't see that, check the image below 

![image](https://user-images.githubusercontent.com/4216599/85474009-74540880-b58a-11ea-81ba-e43b253a4352.png)

(I've also tried doing a hard refresh but the output is the same)

**Comment by penandlim** [comment]
Oh yeah that just means your address was not present in the BAL data set of each week.

---
On a related note:

Did more research about this and seems like i mistakenly thought all of the BAL rewards are present in the data set. 

Found out that BAL earned through Synthetix pools are redirected like so https://github.com/balancer-labs/bal-mining-scripts/blob/master/redirect.json

You can see that [Synthetix PDAO contract](https://etherscan.io/address/0xeb3107117fead7de89cd14d463d340a2e6917769#tokentxns) (Distributor used to distribute SNX) has all of the BAL currently. Im guessing Synthetix team is working hard right now to get them into our wallets :) I'd say wait a bit and monitor their twitter or discord channel :)

(p.s. it helps my weak ass hands to not sell on day 1)

**Comment by penandlim** [comment]
![image](https://user-images.githubusercontent.com/4276174/85475315-c38a4100-b56a-11ea-8b27-08dd1087bf73.png)

**Comment by mattiascaricato** [comment]
awesome! Thanks for the info
