### ISSUE TITLE
iBTC pool incentive : Wrong weekly reward value

### ISSUE THREAD

**Issue by Neozaru** [yieldfarming/yield-farming#8]
https://yieldfarming.info/synthetix/ibtc/

Weekly SNX reward is displayed as 64000 SNX whereas public announcement states a reward of 16000 (per week, 64000 expected total).

**Comment by penandlim** [comment]
https://github.com/yieldfarming/yieldfarming/commit/3954176569bcfb035da894333a99b8a693cc911f
Fixed. Root cause was logic change in synthetix's reward contract.
