### ISSUE TITLE
Add Ren as the pool provider for the Synthetix Curve sBTC pool and a link under the yield farming section

### ISSUE THREAD

**Issue by amcassetti** [yieldfarming/yield-farming#9]
- The sBTC/renBTC/wBTC Curve pool is being funded by both REN (Ren team) and SNX (Synthetix team)
- Ren isn't linked to anywhere on the site

Could we get some love here?

**Comment by penandlim** [comment]
Ahh yeah sorry about that!! I made sure to add REN in the thumbnail but forgot to add it to the main page lmao

Will add some links to REN along with some info

**Comment by amcassetti** [comment]
All good! Thanks a bunch

**Comment by penandlim** [comment]
https://github.com/yieldfarming/yieldfarming/commit/ade2f4beaa39e35e96b61993d734a85a124c1326
